name: entropy CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: [3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install package and requirements
        run: python -m pip install -e .[dev,doc]
      - name: Build documentation
        run: python setup.py build_sphinx
      - name: Run mypy
        run: mypy entropy
      - name: Run black
        run: black -l 79 -q entropy
